/**
 * execution-event.ts
 *
 * Event-Driven Execution Timeline Data Models.
 * Represents immutable execution events generated by tools, tasks, and system actions.
 */

export type ExecutionEventType =
  | 'tool_started'
  | 'tool_completed'
  | 'tool_failed'
  | 'artifact_created'
  | 'file_modified'
  | 'terminal_finished'
  | 'checkpoint_saved';

export interface ExecutionEvent<T = Record<string, unknown>> {
  readonly id: string; // e.g. evt_01JABP8N8P...
  readonly sessionId: string;
  readonly turnId: string;
  readonly taskId: string;
  readonly toolId: string;
  readonly type: ExecutionEventType;
  readonly timestamp: string;
  readonly durationMs: number;
  readonly success: boolean;
  readonly payload: T;
}

let eventCounter = 0;

/**
 * Helper to generate a unique execution event ID with timestamp and sequence counter.
 */
export function generateExecutionEventId(): string {
  eventCounter = (eventCounter + 1) % 100000;
  return `evt_${Date.now()}_${eventCounter.toString().padStart(5, '0')}`;
}
