/**
 * execution-event.ts
 *
 * Event-Driven Execution Timeline Data Models.
 * Represents immutable execution events generated by tools, tasks, and system actions.
 */
export type ExecutionEventType = 'tool_started' | 'tool_completed' | 'tool_failed' | 'artifact_created' | 'file_modified' | 'terminal_finished' | 'checkpoint_saved';
export interface ExecutionEvent<T = Record<string, unknown>> {
    readonly id: string;
    readonly sessionId: string;
    readonly turnId: string;
    readonly taskId: string;
    readonly toolId: string;
    readonly type: ExecutionEventType;
    readonly timestamp: string;
    readonly durationMs: number;
    readonly success: boolean;
    readonly payload: T;
}
/**
 * Helper to generate a unique execution event ID with timestamp and sequence counter.
 */
export declare function generateExecutionEventId(): string;
