"use strict";
/**
 * execution-event.ts
 *
 * Event-Driven Execution Timeline Data Models.
 * Represents immutable execution events generated by tools, tasks, and system actions.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.generateExecutionEventId = generateExecutionEventId;
let eventCounter = 0;
/**
 * Helper to generate a unique execution event ID with timestamp and sequence counter.
 */
function generateExecutionEventId() {
    eventCounter = (eventCounter + 1) % 100000;
    return `evt_${Date.now()}_${eventCounter.toString().padStart(5, '0')}`;
}
//# sourceMappingURL=execution-event.js.map